[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gnc_prototype_algorithms"
version = "0.1.0"
description = "Python and C++ Monorepo for prototyping GNC systems"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]